In [4]:
import pandas as pd

data = {'X':[78,85,96,80,86],
        'Y':[84,94,89,83,86],
        'Z':[86,97,96,72,83]}

df = pd.DataFrame(data)
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [5]:
import pandas as pd
import numpy as np

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
             'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no',
                'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(exam_data, index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [6]:
print(df[['name', 'score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

In [7]:
print(df.loc[['b','d','f','g'], ['name','score']])

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

In [8]:
print(df[df['attempts'] > 2])

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [9]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 10
Columns: 4

In [10]:
print(df.shape)

(10, 4)

In [11]:
print(df[df['score'].isna()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [12]:
print(df[(df['score'] >= 15) & (df['score'] <= 20)])

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

In [13]:
print(df[df['score'].between(15,20)])

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

In [14]:
df.loc['d','score'] = 11.5
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [15]:
print("Total Attempts:", df['attempts'].sum())

Total Attempts: 19

In [16]:
print("Mean score:", df['score'].mean())

Mean score: 13.333333333333334

In [17]:
print(df.loc['a'])
print(df.loc['a':'c'])

name        Anastasia
score            12.5
attempts            1
qualify           yes
Name: a, dtype: object
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [18]:
print(df.iloc[:3])

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [40]:
print(df.columns)

Index(['name', 'score', 'attempts', 'qualify'], dtype='object')

In [51]:
df[df['Age'] >= 31]

      Name  Age  Salary
1   Sutton   32   60000
3  Ravshan   31   70000

In [53]:
import pandas as pd

data = {
    'Name': ['Teodosija', 'Sutton', 'Taneli', 'Ravshan', 'Ross'],
    'Age': [26, 32, 25, 31, 28],
    'Salary': [50000, 60000, 45000, 70000, 55000]
}

df = pd.DataFrame(data)

In [54]:
selected_rows = df[(df['Age'] > 25) & (df['Salary'] > 50000)]
print(selected_rows)

      Name  Age  Salary
1   Sutton   32   60000
3  Ravshan   31   70000
4     Ross   28   55000

In [23]:
df_no_duplicates = df.drop_duplicates()
print(df_no_duplicates)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [24]:
import numpy as np

array_1d = np.array([1,2,3,4,5,6,7,8])
array_2d = array_1d.reshape((2,4))

print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]

In [ ]:
df.loc['P003']
df.loc['P002':'P004', ['Product','Price']]
df.loc[df['Category'] == 'Electronics']

In [28]:
df.iloc[:3]
df.iloc[[1,3]]
df.iloc[-2:, :2]

    name  score
i  Kevin    8.0
j  Jonas   19.0

In [70]:
print(df.columns.tolist())

['Name', 'Age', 'Salary']

In [74]:
df[df['Department'] == 'IT']

   Name Department  Salary  Years  Remote
0  John         IT   75000      3    True
2  Mike         IT   80000      7    True

In [77]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['John', 'Sarah', 'Mike', 'Emma', 'Chris', 'Anna'],
    'Department': ['IT', 'HR', 'IT', 'Sales', 'Sales', 'HR'],
    'Salary': [75000, 65000, 80000, 55000, 58000, 62000],
    'Years': [3, 5, 7, 2, 4, 6],
    'Remote': [True, False, True, False, True, False]
})

In [78]:
df[df['Department'] == 'IT']
df[df['Salary'] > 60000]
df[df['Remote'] == True]
df[df['Years'] >= 5]

    Name Department  Salary  Years  Remote
1  Sarah         HR   65000      5   False
2   Mike         IT   80000      7    True
5   Anna         HR   62000      6   False

In [68]:
df.loc[df['Age'] > 28].iloc[:2]

df.loc[2,'Salary']
df.iloc[2]['Salary']

np.int64(45000)

In [79]:
df[(df['Department']=='IT') & (df['Remote']==True)]

df[(df['Salary'].between(60000,75000)) & (df['Years']>3)]

df[(df['Department']!='HR') & (df['Salary']>60000)]

   Name Department  Salary  Years  Remote
0  John         IT   75000      3    True
2  Mike         IT   80000      7    True

In [80]:
df[(df['Department']=='IT') | (df['Remote']==True)]

df[(df['Salary']<60000) | (df['Salary']>70000)]

df[(df['Department']=='Sales') | (df['Years']<3)]

    Name Department  Salary  Years  Remote
3   Emma      Sales   55000      2   False
4  Chris      Sales   58000      4    True

In [82]:
print(df.columns)

Index(['Name', 'Department', 'Salary', 'Years', 'Remote'], dtype='object')

In [ ]:
df[((df['Region']=='North') | (df['Region']=='South')) & (df['Revenue']>1200)]

In [83]:
import pandas as pd

df = pd.DataFrame({
    'Date': pd.date_range('2024-01-01', periods=10),
    'Region': ['North', 'South', 'East', 'West', 'North', 
               'South', 'East', 'West', 'North', 'South'],
    'Product': ['A', 'B', 'A', 'C', 'B', 
                'A', 'C', 'B', 'A', 'C'],
    'Quantity': [10, 15, 8, 20, 12, 
                 25, 18, 22, 14, 30],
    'Revenue': [1000, 1500, 800, 2000, 1200, 
                2500, 1800, 2200, 1400, 3000]
})

In [84]:
df[((df['Region']=='North') | (df['Region']=='South')) & 
   (df['Revenue'] > 1200)]

        Date Region Product  Quantity  Revenue
1 2024-01-02  South       B        15     1500
5 2024-01-06  South       A        25     2500
8 2024-01-09  North       A        14     1400
9 2024-01-10  South       C        30     3000

In [85]:
df[((df['Region']=='North') | (df['Region']=='South')) & (df['Revenue']>1200)]

df[(df['Product'].isin(['A','B'])) & (df['Quantity'].between(10,20))]

df[(df['Region']!='West') & (df['Revenue'] >= df['Revenue'].quantile(0.5))]

        Date Region Product  Quantity  Revenue
5 2024-01-06  South       A        25     2500
6 2024-01-07   East       C        18     1800
9 2024-01-10  South       C        30     3000